### ISSUE TITLE
Presentation sections

### ISSUE THREAD

**Issue by AntoinePrv** [hadisinaee/avicenna#23]
Hello,

I think it would be beneficial to have a _Presentation_ section similar to the publication.
IMO in academia, researchers like to upload the slides to some their presentation and not all presentations are linked to a publication.

I will be working on this for myself (mostly a copy of `publication`), and I'll happily send a PR if you're interested.

Thank you for the project

**Comment by hadisinaee** [comment]
Hi @AntoinePrv,

Sure, that's great. I'd be glad to see that. I try my bests to review and merge all PRs ASAP. There are very good suggestions and works in my to-do list for Avicenna. I hope to find a free slot in my calendar to work on those.

Thank _you_ :)

**Comment by AntoinePrv** [comment]
I'm currently thinking that I would actually like to have more sections (tutorial, poster, grants...), but this would start being too redundant and specific to my needs to merge back into Avicenna.

I think the clean way to go would be to have _meta section_, where one would specify a `title` parameter. The subsections would then be processed as it is done for publications...

On the plus side, it gives a lot of flexibility and reduce code duplication (could also be used to implement `publication` and `projects`). However, it may add too much complexity.

Here is a sample config (option 1)
```toml
[[params.sections]]
  title="My Presentations"

  [[params.sections.subsections]]
    title="2019"

    [[params.sections.subsections.items]]
      name="My title"
      author="Some people"
```

It is a bit verbose, so an idea could be to use the keys for title (option 2):
(**Edit**: it is not ideal because keys are case insensitive.)
```toml
[[params.sections."My Presentations".2019]]
  name="My title"
  author="Some people"
```

What are your thoughts on this ?
