### ISSUE TITLE
Social icons not showing

### ISSUE THREAD

**Issue by AntoinePrv** [hadisinaee/avicenna#6]
Hello,

Thank you for providing this simple, clean personal page template.
I'm not an expert in web development, and this is the first time I am using Hugo.

In the default template, without making changes, the config contains:
```toml
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/hadisinaee"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/hadisinaee"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/hadisinaee/"
```

However, when serving the website, only the Github icon is showing.

I believe the excepted behaviour should be similar to the [screenshot](https://themes.gohugo.io/avicenna/)

Thank you again for your time.
